[project]
name = 'clunkster'
version = '0.1.0'
description = 'Add your description here'
readme = 'README.md'
requires-python = '>=3.14'
dependencies = []

[dependency-groups]
dev = [
    'deptry>=0.25.1',
    "gmcodec",
    "griffe>=2.1.0",
    "griffe-inherited-docstrings>=1.1.3",
    "griffelib>=2.1.0",
    "mdformat>=1.0.0",
    "mdformat-gfm>=1.0.0",
    "mdformat-pyproject>=0.1.1",
    "mdformat-ruff>=0.1.3",
    "pillow>=12.2.0",
    "pyahocorasick>=2.3.1",
    "pygments>=2.20.0",
    'pytest>=9.0.3',
    "rich>=15.0.0",
    'ruff>=0.15.14',
    "rustworkx>=0.17.1",
    "tqdm>=4.67.3",
    'ty>=0.0.38',
    "zensical>=0.0.46",
]

[tool.pytest.ini_options]
testpaths = ['tests']
python_files = 'test_*.py'
addopts = '-v --tb=short'

[tool.ruff]
target-version = 'py314'
line-length = 79
fix = true

[tool.ruff.format]
quote-style = 'single'
docstring-code-format = false

exclude = ["scripts/readme.py"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.isort]
known-first-party = ['clunkster']

[tool.ruff.lint]
select = [
    'A',
    'ANN',
    'B',
    'BLE',
    'C4',
    'C90',
    'COM',
    'D',
    'DTZ',
    'E',
    'ERA',
    'EXE',
    'F',
    'FBT',
    'FLY',
    'FURB',
    'G',
    'I',
    'ICN',
    'ISC',
    'LOG',
    'N',
    'PERF',
    'PGH',
    'PIE',
    'PLR',
    'PT',
    'PTH',
    'Q',
    'RET',
    'RSE',
    'RUF',
    'S',
    'SIM',
    'SLF',
    'SLOT',
    'T100',
    'TRY',
    'UP',
    'W',
    'YTT',
]

ignore = [
    # trailing comma, conflicts with `ruff format`
    'COM812',

    # implicit string concat conflicts with `ruff format`
    'ISC001',

    # prefer explicit string concat over implicit concat
    'ISC003',

    # long exception messages from `tryceratops`
    'TRY003',

    # this rule always does false positives
    'D401',

    # allow asserts in simple projects
    'S101',

    # this isn't backend or anything
    'S324',

    # conflicting rules

    # prefer no blank line before class docstring
    'D203',
    # prefer multiline summary being placed on """ line
    'D213',

    # thoumstve dared against luigi
    'D404'
]

[tool.ruff.lint.extend-per-file-ignores]
'main.py' = [
    'ERA001',

    # example complexity is dictated by soul
    'C901',
    'PLR0912',
]

'scripts/readme.py' = [
    # no line length error in doc file
    'E501'
]

[tool.deptry.per_rule_ignores]
DEP004 = [
    'mdformat',
    'griffe'
]

[tool.uv.sources]
gmcodec = { git = "https://github.com/shaperones0/gmcodec.git" }
[tool.deptry]
extend_exclude = [ "main.py" ]
