[project]
name = 'clunkster'
version = '0.1.0'
description = 'Add your description here'
readme = 'README.md'
requires-python = '>=3.14'
dependencies = []

[dependency-groups]
runtime = [
    'gmcodec',
    'pillow>=12.3.0',
    'pyahocorasick>=2.3.1',
    'rich>=15.0.0',
    'rustworkx>=0.18.0',
]

dev = [
    { include-group = 'runtime' },
    'deptry>=0.25.1',
    'griffe>=2.1.0',
    'griffe-inherited-docstrings>=1.1.3',
    'griffelib>=2.1.0',
    'markdown>=3.10.2',
    'pre-commit>=4.6.2',
    'pygments>=2.20.0',
    'pytest>=9.1.1',
    'ruff>=0.15.20',
    'ty>=0.0.57',
    'zensical>=0.0.47',
]

[tool.pytest.ini_options]
testpaths = ['tests']
python_files = 'test_*.py'
addopts = '-v --tb=short'

[tool.ruff]
target-version = 'py314'
line-length = 79
fix = true

[tool.ruff.format]
quote-style = 'single'
docstring-code-format = false
preview = true

exclude = ['scripts/readme.py']

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.isort]
known-first-party = ['clunkster']

[tool.ruff.lint]
preview = true
select = [
    'A',
    'ANN',
    'B',
    'BLE',
    'C4',
    'C90',
    'COM',
    'D',
    'DTZ',
    'E',
    'ERA',
    'EXE',
    'F',
    'FBT',
    'FLY',
    'FURB',
    'G',
    'I',
    'ICN',
    'ISC',
    'LOG',
    'N',
    'PERF',
    'PGH',
    'PIE',
    'PLR',
    'PT',
    'PTH',
    'Q',
    'RET',
    'RSE',
    'RUF',
    'S',
    'SIM',
    'SLF',
    'SLOT',
    'debugger',
    'TRY',
    'UP',
    'W',
    'YTT',
]

ignore = [
    # trailing comma, conflicts with `ruff format`
    'missing-trailing-comma',

    # implicit string concat conflicts with `ruff format`
    'single-line-implicit-string-concatenation',

    # prefer explicit string concat over implicit concat
    'explicit-string-concatenation',

    # long exception messages from `tryceratops`
    'raise-vanilla-args',

    # this rule always does false positives
    'non-imperative-mood',

    # allow asserts in simple projects
    'assert',

    # this isn't backend or anything
    'hashlib-insecure-hash-function',

    # stupid complexity rules for BABIES
    'complex-structure',
    'too-many-branches',
    'too-many-locals',
    'too-many-statements',
    'magic-value-comparison',  # bruv thinks every number is magic

    # conflicting rules

    # prefer no blank line before class docstring
    'incorrect-blank-line-before-class',
    # prefer multiline summary being placed on """ line
    'multi-line-summary-second-line',

    # thoumstve dared against luigi
    'docstring-starts-with-this'
]

[tool.ruff.lint.extend-per-file-ignores]
'main.py' = [
    'commented-out-code',

    # example complexity is dictated by soul
    'complex-structure',
    'too-many-branches',
]

'scripts/readme.py' = [
    # no line length error in doc file
    'line-too-long'
]

[tool.ty.rules]
all = 'error'

[tool.deptry.per_rule_ignores]
DEP004 = [
    'griffe',
    'markdown',
]

[tool.uv.sources]
gmcodec = { git = 'https://github.com/shaperones0/gmcodec.git' }
[tool.deptry]
extend_exclude = [ 'main.py' ]
