from abc import ABC, abstractmethod
from typing import Self, override
import collections.abc as col
from dataclasses import dataclass
import re

from scripts import doc_imports, doc_parse, doc_extract
from scripts.doc_snippets import Snippet, SnippetType


def str_to_anchor(text: str) -> str:
    """Convert string to Markdown anchor.

    :param text: Text to convert.
    :return: Safe anchor.
    """
    return re.sub(r'\s+', '-', re.sub(r'[^\w\-\s]', '', text.lower()))


class Header(ABC):
    @abstractmethod
    @property
    def header_full(self) -> str:
        """Full header."""

    @abstractmethod
    @property
    def header_mini(self) -> str:
        """Minified header."""

    @abstractmethod
    @property
    def level(self) -> int:
        """Header's level."""

    def render_header(self) -> str:
        """Render Markdown header with correct numbering.

        :return: Generated Markdown string.
        """
        return f'{'#' * self.level} {self.header_full}'

    def render_href(self, text: str | None = None) -> str:
        """Render a link to this header.

        :param text: Text to insert into the link.
        :return: Rendered header.
        """
        if text is None:
            text = self.header_mini
        return f'[{text}](#{str_to_anchor(self.header_full)})'


class HeaderSimple(Header):

    def __init__(self, level: int, header: str, header_mini: str | None = None) -> None:
        self._level = level
        self._header = header
        if header_mini is None:
            self._header_mini = header
        else:
            self._header_mini = header_mini

    @property
    def header_full(self) -> str:
        return self._header

    @property
    def header_mini(self) -> str:
        return self._header_mini

    @property
    def level(self) -> int:
        return self._level


@dataclass(frozen=True, slots=True)
class ExampleHeader(Header):
    """Autogenerated Markdown header of an example."""

    @property
    def level(self) -> int:
        return 3

    header: str
    idx: int | tuple[int, ...] | None = None

    def header_num(self) -> str:
        if self.idx is None:
            return ''
        if isinstance(self.idx, int):
            return str(self.idx)
        return '.'.join(map(str, self.idx))

    @override
    @property
    def header_full(self) -> str:
        """Generate example's full title.

        :return: Example's title.
        """
        num = self.header_num()
        return f'Example {(num + ' - ') if num else ''}{self.header}'

    @override
    @property
    def header_mini(self) -> str:
        """Generate example's minified title.

        :return: Example's minified title.
        """
        return f'ex{self.header_num()}'


class HeaderGenerator(ABC):
    @abstractmethod
    def reset(self) -> None:
        """Reset the header generator."""

    @abstractmethod
    def next_header(self, title: str) -> Header:
        """Generate next header."""


class ExampleHeaderGenerator(HeaderGenerator):
    def __init__(self, *, idx_major_start: int = 0, idx_minor_start: int = 0) -> None:
        self.idx_major_start = idx_major_start
        self.idx_minor_start = idx_minor_start
        self.current_idx_major = idx_major_start
        self.current_idx_minor = idx_minor_start

    def reset(self) -> None:
        self.current_idx_major = self.idx_major_start
        self.current_idx_minor = self.idx_minor_start

    def next_section(self, title: str) -> HeaderSimple:
        self.current_idx_major += 1
        self.current_idx_minor = self.idx_minor_start
        return HeaderSimple(
            level=2,
            header=title,
        )

    def next_header(self, title: str) -> ExampleHeader:
        self.current_idx_minor += 1
        return ExampleHeader(
            header=title,
            idx=(self.current_idx_major, self.current_idx_minor),
        )
