"""Inject examples into readme."""

import collections.abc as col
import itertools as it
from dataclasses import dataclass
from pathlib import Path
from typing import Self, override

import scripts.readme_docstring as my_docstring
import scripts.readme_imports as my_imports
from scripts.readme_snippets import (
    Snippet,
    SnippetExtractor,
    SnippetType,
    snippets_render,
)
from scripts.readme_toc import str_to_anchor


def gen_stub_cls(*names: str) -> str:
    """Generate stub classes.

    :param names: Class names.
    :return: Python code with stub classes.
    """
    return '\n'.join(f'class {name}: ...' for name in names)


def gen_stub_var(*names: str) -> str:
    """Generate stub variables.

    :param names: Variable names (can include type hints).
    :return: Python code with stub variables.
    """
    return '\n'.join(f'{name} = ...' for name in names)


@dataclass(frozen=True, slots=True)
class ExampleHeader:
    """Autogenerated Markdown header of an example."""

    header: str
    idx_major: int
    idx_minor: int

    def _header(self) -> str:
        return f'Example {self.idx_major}.{self.idx_minor} - {self.header}'

    def _header_mini(self) -> str:
        return f'ex{self.idx_major}.{self.idx_minor}'

    def render_header(self) -> str:
        """Render Markdown header with correct numbering.

        :return: Generated Markdown string.
        """
        return f'### {self._header()}'

    def render_href(self, text: str | None = None) -> str:
        """Render a link to this example.

        :param text: Text to insert into the link
        :return:
        """
        if text is None:
            text = self._header_mini()
        return f'[{text}](#{str_to_anchor(self._header())})'


ExampleContent = tuple[Snippet, ...]


@dataclass(frozen=True, slots=True)
class Example:
    """Example definition, with headers."""

    name: str
    header_section: str
    header_title: str
    content: ExampleContent


class ExampleManager:
    """Manager for examples."""

    def __init__(
        self,
        *,
        snippets: SnippetExtractor,
        imports: my_imports.ImportsFilter,
        docs: dict[str, str],
    ) -> None:
        """Create manager of examples from a file.

        :param snippets: Extracted snippets from target file.
        :param imports: Extracted imports from target file.
        :param docs: Extracted docstrings from target file.
        """
        self.snippets = snippets
        self.imports = imports
        self.docs = docs

        self.stubs: dict[str, str] = {}

        self.examples: dict[str, Example] = {}

    @classmethod
    def from_file_path(cls, file_path: str) -> Self:
        """Generate manager of examples from given file path.

        :param file_path: File path to extract stuff from.
        :return: Generated example manager.
        """
        return cls(
            snippets=SnippetExtractor.from_file_path(file_path),
            imports=my_imports.ImportsFilter.from_file_path(file_path),
            docs=my_docstring.extract_file(file_path),
        )

    def stub_register(self, snippet_name: str, stub: str) -> None:
        """Register a stub version of a given snippet.

        :param snippet_name: Name of the replaced snippet.
        :param stub: Stub Python code.
        """
        self.stubs[snippet_name] = stub

    def _process_refs(
        self, refs: col.Iterable[str]
    ) -> col.Iterator[tuple[Snippet, ...]]:
        for ref in refs:
            if ref.isupper():
                if ref[0] == '!':
                    # paste stub by name
                    yield (Snippet.from_code(self.stubs[ref[1:]]),)

                else:
                    # paste snippet by name
                    yield tuple(self.snippets.extract(ref))
            else:
                # paste code as is
                yield (Snippet.from_code(ref),)

    def gen_freeform(
        self,
        *,
        func_name: str,
        refs: col.Iterable[str],
        gen_imports: bool = True,
    ) -> ExampleContent:
        """Generate example content.

        :param func_name: Function to fetch docstring from to use as a header.
          Blank for no header.
        :param refs: Code pieces or snippets. Ones that are all uppercase
          are considered snippet names and will be fetched from main file.
          Start with ! to include as a stub.
        :param gen_imports: Whether to insert imports generated from all
          code pieces after the header.
        :return: Generated document in a form of snippet collection.
        """
        snip_docs = (
            Snippet.from_md(self.docs[func_name]) if func_name else None
        )
        snips_mains: list[tuple[Snippet, ...]] = list(self._process_refs(refs))

        snips_code: list[str] = []
        for snips in snips_mains:
            snips_code.extend(
                snip.content
                for snip in snips
                if snip.type == SnippetType.PYTHON
            )

        snip_imports = (
            Snippet.from_code(self.imports.filter_used_unparse(*snips_code))
            if gen_imports
            else None
        )

        return tuple(
            it.chain(
                (snip_docs,) if snip_docs else (),
                (snip_imports,) if snip_imports else (),
                *snips_mains,
            )
        )


class Renderable:
    """Base Markdown renderable piece."""

    def render(self) -> str:
        """Render this piece.

        :return: Rendered Markdown string.
        """
        raise NotImplementedError


class RenderableSectionTitle(Renderable):
    """Renderable section title."""

    def __init__(self, section_title: str, section_idx: int) -> None:
        """Create section from title and index.

        Resulting section is "## <idx> - <title>".
        :param section_title: Section title.
        :param section_idx: Section index.
        """
        self.section_title = section_title
        self.section_idx = section_idx

    @override
    def render(self) -> str:
        """Render this section title.

        :return: Section title rendered as heading.
        """
        return f'## {self.section_idx} - {self.section_title}'


class RenderableHeader(Renderable):
    """Renderable example header."""

    def __init__(self, header: ExampleHeader) -> None:
        """Create renderable header from example header.

        :param header:
        """
        self.header = header

    def render(self) -> str:
        """Render the underlying example header.

        :return: Rendered heading.
        """
        return self.header.render_header()


class RenderableContent(Renderable):
    """Renderable collection of snippets."""

    def __init__(self, content: ExampleContent) -> None:
        """Create renderable content from snippets.

        :param content: Snippets collection.
        """
        self.content = content

    def render(self) -> str:
        """Render the snippets.

        :return: Rendered Markdown document.
        """
        return snippets_render(*self.content)


class ExampleRenderer:
    """Renderer for examples."""

    def __init__(
        self,
        renderables: list[Renderable],
        name2header: dict[str, ExampleHeader],
    ) -> None:
        """Create an example renderer.

        :param renderables: Sequence of renderables.
        :param name2header: Example name to its header index.
        """
        self.renderables = renderables
        self.name2header = name2header

    @classmethod
    def from_examples(cls, examples: list[Example]) -> Self:
        """Generate renderables from list of examples.

        :param examples: Examples to render.
        :return: Prepared renderer.
        """
        renderables: list[Renderable] = []

        sections: set[str] = set()
        title_count = 0
        last_section: str | None = None
        name2header: dict[str, ExampleHeader] = {}

        for example in examples:
            cur_section = example.header_section
            if not cur_section:
                assert last_section is not None
                cur_section = last_section
            if cur_section != last_section:
                title_count = 0
                last_section = cur_section
                if cur_section in sections:
                    raise ValueError(
                        f'Duplicate or misplaced section {cur_section}'
                    )
                sections.add(cur_section)
                renderables.append(
                    RenderableSectionTitle(cur_section, len(sections))
                )

            title_count += 1
            header = ExampleHeader(
                header=example.header_title,
                idx_major=len(sections),
                idx_minor=title_count,
            )
            if example.name in name2header:
                raise ValueError(f'Duplicate example name {example.name}')
            name2header[example.name] = header
            renderables.append(RenderableHeader(header))
            renderables.append(RenderableContent(example.content))

        return cls(renderables=renderables, name2header=name2header)

    def href(self, name: str, text: str | None = None) -> str:
        """Generate a Markdown link to specified example.

        :param name: Example name.
        :param text: Text to put into the link, by default is
          example's heading.
        :return: Rendered link.
        """
        return self.name2header[name].render_href(text)

    def render(self) -> str:
        """Render the examples.

        :return: Rendered Markdown block.
        """
        return '\n'.join(bit.render() for bit in self.renderables)


def main_manager(
    file_path: str = 'main.py',
) -> tuple[ExampleManager, ExampleRenderer]:
    """Generate example manager and renderer for our project.."""
    exs = ExampleManager.from_file_path(file_path)
    exs.stub_register('CLS_ASSET_TYPE', gen_stub_cls('AssetType'))
    exs.stub_register('CLS_ASSET', gen_stub_cls('Asset'))
    exs.stub_register('CLS_DEPENDENCY', gen_stub_cls('Dependency'))
    exs.stub_register('VAR_ASSETS', gen_stub_var('assets: list[Asset]'))
    exs.stub_register(
        'VAR_DEPS', gen_stub_var('dependencies: list[Dependency]')
    )

    examples: list[Example] = [
        Example(
            'ex_start',
            'Reading project',
            'Finding assets',
            content=exs.gen_freeform(
                func_name='main_ex_start',
                refs=[
                    'CLS_ASSET_TYPE',
                    'CLS_ASSET',
                    'CLUSTERABLE_BUILTINS',
                    'PROJECT',
                    'MAIN_EX_START',
                ],
            ),
        ),
        Example(
            'ex_clusters',
            'Reading project',
            'Generating clusters',
            content=exs.gen_freeform(
                func_name='main_ex_clusters',
                refs=[
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    'CLUSTERABLE_ASSETS',
                    'PROJECT',
                    'MAIN_EX_CLUSTERS',
                ],
            ),
        ),
        Example(
            'ex_aliases',
            'Reading project',
            'Cluster aliasing',
            content=tuple(
                it.chain(
                    exs.gen_freeform(
                        func_name='main_ex_aliases',
                        refs=[
                            'ALIAS',
                            'MAIN_EX_ALIAS_GIST_INVERT',
                            'MAIN_EX_ALIAS_GIST_ALIAS',
                        ],
                        gen_imports=False,
                    ),
                    (Snippet.from_md('Full example:'),),
                    exs.gen_freeform(
                        func_name='',
                        refs=[
                            'CLS_ASSET_TYPE',
                            'CLS_ASSET',
                            'ALIAS',
                            'CLUSTERABLE_ASSETS',
                            'PROJECT',
                            'MAIN_EX_ALIASES',
                        ],
                    ),
                )
            ),
        ),
        Example(
            'ex_scan_sync',
            'References',
            'Reference scanning',
            content=exs.gen_freeform(
                func_name='main_ex_scan_sync',
                refs=[
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    '!VAR_ASSETS',
                    'MAIN_EX_SCAN_SYNC',
                ],
            ),
        ),
        Example(
            'ex_scan_sync2',
            'References',
            'Reference scanning (fancier)',
            content=exs.gen_freeform(
                func_name='main_ex_scan_sync2',
                refs=[
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    'CLS_DEPENDENCY',
                    '!VAR_ASSETS',
                    'MAIN_EX_SCAN_SYNC2',
                ],
            ),
        ),
        Example(
            'ex_scan_mp',
            'References',
            'Reference scanning (multiprocessing)',
            content=exs.gen_freeform(
                func_name='main_ex_scan_mp',
                refs=[
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    'CLS_SCAN_JOB',
                    'CLS_DEPENDENCY',
                    'REG_WORKERS_EXPLAIN',
                    'REG_WORKERS',
                    '!VAR_ASSETS',
                    'MAIN_EX_SCAN_MP',
                ],
            ),
        ),
        Example(
            'ex_lint_unused',
            'References',
            'Lint: unused assets',
            content=exs.gen_freeform(
                func_name='main_ex_lint_unused',
                refs=[
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    '!CLS_DEPENDENCY',
                    '!VAR_ASSETS',
                    '!VAR_DEPS',
                    'MAIN_EX_LINT_UNUSED',
                ],
            ),
        ),
        Example(
            'ex_lint_crossref',
            'References',
            'Lint: cross-cluster references',
            content=exs.gen_freeform(
                func_name='main_ex_lint_crossref',
                refs=[
                    'LINT_RULES',
                    'CONTEXT_RULES',
                    '!CLS_ASSET_TYPE',
                    '!CLS_ASSET',
                    '!CLS_DEPENDENCY',
                    '!VAR_DEPS',
                    'MAIN_EX_LINT_CROSSREF',
                ],
            ),
        ),
    ]

    rend = ExampleRenderer.from_examples(examples)

    return exs, rend


def main_test() -> None:
    """Test shim."""
    _exs, _rend = main_manager(str(Path(__file__).parent.parent / 'main.py'))
    print(_rend.render())


if __name__ == '__main__':
    main_test()
